name: Workflows, Jobs, and Steps

on:
  workflow_dispatch:
    
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "A job consists of"
      - run: echo "one or more steps running on ubuntu-latest"
  
  job-2:
    runs-on: ubuntu-slim
    steps:
      - run: echo "jobs can run in parallel - using different runners"
  
  job-3:
    runs-on: ubuntu-24.04
    needs:
      - job-1
      - job-2
    steps:
      - run: echo "Runs after other jobs complete using 'needs'"