name: Using javascript code on action

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Hello World Action
        id: hello
        uses: ./.github/actions/javascript-action
        with:
          name: 'GitHub'
      
      - name: Display Output
        run: "echo \"The action run at: ${{ steps.hello.outputs.time }}\""
