name: Example GitHub Action Workflow using javascript code

on:
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Hello World Action
        id: hello
        uses: ./.github/actions/javascript-action
        with:
          name: 'GitHub'
      
      - name: Display Greeting
        run: "echo \"The action said: ${{ steps.hello.outputs.greeting }}\""
